{
  "login": "tcrack326",
  "id": 2215681,
  "avatar_url": "https://avatars.githubusercontent.com/u/2215681?v=2",
  "gravatar_id": "",
  "url": "https://api.github.com/users/tcrack326",
  "html_url": "https://github.com/tcrack326",
  "followers_url": "https://api.github.com/users/tcrack326/followers",
  "following_url": "https://api.github.com/users/tcrack326/following{/other_user}",
  "gists_url": "https://api.github.com/users/tcrack326/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/tcrack326/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/tcrack326/subscriptions",
  "organizations_url": "https://api.github.com/users/tcrack326/orgs",
  "repos_url": "https://api.github.com/users/tcrack326/repos",
  "events_url": "https://api.github.com/users/tcrack326/events{/privacy}",
  "received_events_url": "https://api.github.com/users/tcrack326/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Thomas Alan McCracken ",
  "company": "",
  "blog": "",
  "location": "Atlanta, GA",
  "email": "thomas.alan.mccracken@gmail.com",
  "hireable": false,
  "bio": null,
  "public_repos": 10,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2012-08-25T04:18:27Z",
  "updated_at": "2014-10-08T17:42:24Z"
}
